### ISSUE TITLE
how to support linux-aarch64?

### ISSUE THREAD

**Issue by yangxingyu588** [conda-forge/r-gwasexacthw-feedstock#6]
### Comment:

hi, if we want to support linux-aarch64, could you mind tell me what should l do?

**Comment by mfansler** [comment]
Please follow migration directions: https://conda-forge.org/docs/maintainer/knowledge_base.html#using-arch-rebuild-txt

**Comment by mfansler** [comment]
Resolved by #7. Builds should be available in a couple hours.
